'''
Created on 28 lug 2015

@author: DarioConte
'''

from Enumeration import *
from struct import *

class Messaggi(object):
    
    def __init__(self, params):
        pass
    
    #queste servono per il test
    CallBack=Enumeration("cb_NULL cb_mprReceiveData cb_mirReceiveData cb_dllGetLogon cb_aclGetMessage cb_acmGetMessage cb_flipcyRequestRoute cb_ggcGetMessage cb_metGetMsg cb_accGetMessage cb_aerGetMessage cb_mrrGetMessage cb_capGetMsg cb_manGetMessage cb_datisCGetRequest cb_dclGetMessage cb_end ")
    AcgErrors = Enumeration("ae_ok ae_connect ae_readingConfigFile ae_invalidCi ae_invalidParam ae_serviceNotSupported ae_abort ae_noWaitingMessages ae_logonInfoNotAvailable ae_mprAbort ae_mrrAbort ae_mirAbort ae_capDataNotAvailable ae_capNotAvailable ae_capAbort ae_metDataNotAvailable ae_metNotAvailable ae_metAbort ae_tspdSendingMsg ae_tspdOverflow ae_tspdBufferFull ae_tspdStartNotReceived ae_tspdRestarted ae_tspdAbort ae_dllForwardError ae_dllForwardResponseOk ae_dllForwardResponseNok ae_dllLogonResponseError ae_dllContactError ae_dllContactResponseOk ae_dllContactResponseNok ae_dllUpdate ae_dllAbort ae_dllDialogueClosed ae_dllLogonRejected ae_aclClosedDueToTransfer ae_aclIncorrectOriginator ae_aclPendingElements ae_aclRestarted ae_aclStartNotReceived ae_aclmaxNumElements ae_acltooManyElements ae_aclnoElements ae_acltimeoutTr ae_acltimeoutTt ae_aclerrorResponse ae_acldatalinkPerformance ae_aclcompositionRule ae_aclNotPermitted ae_aclMessageRefNotFound ae_aclDeniedConnectionRequest ae_aclConnectionRefused ae_aclGetMessageNotReceived ae_aclNoConnection ae_aclFailureAttemptingConnection ae_aclMessageCannotBeProcessed ae_aclIncorrectMRN ae_aclIncorrectTimestamp ae_aclLackNotRequired ae_aclInvalidElementCombination ae_aclIllegalElement ae_aclInvalidResponse ae_aclDialogNotFound ae_acmTimeoutTr ae_acmTimeoutTt ae_acmPendingAcl ae_acmPendingEs ae_acmPendingVci ae_acmErrorResponse ae_DuplicateMid ae_acmDatalinkPerformance ae_acmDialogueAbort ae_acmDeniedConnectionRequest ae_acmConnectionRefused ae_acmDisconnectionRefused ae_acmCompositionRule ae_DialogueClosed ae_acmNoConnection ae_acmFailureAttemptingConnection ae_acmAlreadyConnected ae_acmUnknownAircraft ae_acmConnected ae_acmDisconnected ae_acmMessageCannotBeProcessed ae_acmIncorrectMRN ae_acmIncorrectTimestamp ae_acmLackNotRequired ae_acmInvalidElementCombination ae_acmIllegalElement ae_acmInvalidResponse ae_acmDialogNotFound ae_flipcyRouteNotAvailable ae_flipcyTimeoutRoute ae_flipcyAbort ae_flipcyClosedDueToTransfer ae_flipcyDeniedConnectionRequest ae_flipcyDatalinkPerformance ae_flipcyDialogOpenAlready ae_flipcyConnectionRefused ae_flipcyNotPermitted ae_flipcyErrorDetected ae_flipcyDialogueClosed ae_flipcyNoConnection ae_flipcyFailureAttemptingConnection ae_atisSendingMsg ae_atisAbort ae_ggcDialogueAbort ae_ggcTimeoutConfirm ae_ggcAbort ae_ggcDialogueClosed ae_ggcErrorDetected ae_AccPeriodicRequestUnderway ae_AccDemandRequestUnderway ae_AccEventRequestUnderway ae_AccEmergencyUpdateUnderway ae_AccUnknownAircraft ae_AccAbort ae_AerAbort ae_datisCError ae_datisCAbort ae_dclError ae_dclAbort ae_623SendingMsg")
    AcgLogonTypes= Enumeration("acg_logonFromAircraft acg_logonFromAtsu")
    AcgDllGetLogonOut={"m_logonType":AcgLogonTypes}
    AcgDllGetLogonReturn = {"m_returnValue": AcgErrors,"m_args":AcgDllGetLogonOut}
    AcgMessageReceive={"m_callback":CallBack,"m_DllArg":AcgDllGetLogonReturn}
    AcgMsgtoSend={"messaggio":AcgMessageReceive,"buffer":0}